---
output: html_document
editor_options: 
chunk_output_type: console
---


# Load data

```{r}
setwd("~/Documents/uni/FIB-ADEI/labs/lab1")
rm(list=ls())

library(AER)
library(car)
library(FactoMineR)
data("SwissLabor")
```

# Take a look

```{r}
df<-SwissLabor
head(df)
summary(df)

# EDA - Univariant - Factor
barplot(table(df$participation))
barplot(table(df$participation),col="cyan",main="Diagram a de Barres")

# EDA - Univariant - Numèrica

hist(df$income)
hist(df$income,15,col=rainbow(8),main="Histograma Income")
hist(df$income,15,freq=F,col=rainbow(8),main="Histograma Income")
boxplot(df$income)
```


```{r}
levels(SwissLabor$participation)<- paste("Parti.",sep="",levels(SwissLabor$participation))
levels(SwissLabor$foreign)<- paste("Foreign.",sep="",levels(SwissLabor$foreign))
````

# Examples 1
```{r}
library(mvoutlier)
names(df)
vout<-aq.plot(df[,2:4], delta=qchisq(0.95, 3,alpha=0.05)
summary(df)
```

# Examples 2
```{r}
library(chemometrics)
dis <- Moutlier(SwissLabor[,2:4], quantile = 0.995)
dis$cutoff
par(mfrow=c(1,1))
plot(dis$md,dis$rd, type="n") text(dis$md,dis$rd,labels=rownames(SwissLabor[,2:4])) abline(h=qchisq(0.995, ncol(SwissLabor[,2:4])),col="red",lwd=2)
SwissLabor$mout<-0
sel<-which(dis$rd>12)
SwissLabor[sel,"mout"]<-1
```

# Examples 3
```{r}
summary(SwissLabor),
llista<-sample(1:nrow(SwissLabor),40),
llista,
df<-SwissLabor,
df[llista,"age"]<-NA, # df[llista, 3]
summary(df),
library(missMDA),

# Numeric imputation <-- only explanatory vars (no trget!!!)
vars_con<-names(df)[2:6],
vars_con,
summary(df[,vars_con]),
res.input<-imputePCA(df[,vars_con],ncp=4),
str(res.input),
summary(res.input$completeObs),

# MUST (validation)
par(mfrow=c(1,3)),
hist(df$age,col="red")
hist(SwissLabor$age,col="green")
hist(res.input$completeObs[,2],col="blue")

quantile(df$age,seq(0,1,0.1),na.rm=T) ,
quantile(SwissLabor$age,seq(0,1,0.1),na.rm=T), 
round(quantile(res.input$completeObs[,2],seq(0,1,0.1),na.rm=T),dig=1),
```

# Examples 4
```{r}
llista<-sample(1:nrow(SwissLabor),40);
llista 
df<-SwissLabor;
df[llista,"participation"]<-NA;
summary(df)

library(missMDA)
# Categorical imputation
vars_dis<-names(df)[c(1,7)]
summary(df[,vars_dis])

nb <- estim_ncpMCA(df[, vars_dis],ncp.max=25) 
res.input<-imputeMCA(df[,vars_dis]) 
summary(res.input$completeObs)

# MUST (validation)
par(mfrow=c(1,3))
barplot(table(df$participation, col="red"))
barplot(table(SwissLabor$participation, col="green"))
barplot(table(res.input$completeObs, col="blue"))

```