---
output: html_document
editor_options: 
  chunk_output_type: console
---


# Load data

```{r}
setwd("D:/DOCENCIA/FIB-ADEI/EXEMPLES-TEO")
rm(list=ls())

library(AER)
library(car)
library(FactoMineR)
data("SwissLabor")
```

# Take a look

```{r}
df<-SwissLabor
head(df)
summary(df)

# EDA - Univariant - Factor
barplot(table(df$participation))
barplot(table(df$participation),col="cyan",main="Diagram a de Barres")

# EDA - Univariant - Numèrica

hist(df$income)
hist(df$income,15,col=rainbow(8),main="Histograma Income")
hist(df$income,15,freq=F,col=rainbow(8),main="Histograma Income")
boxplot(df$income)

```

September 30th, 2020

```{r}
df$participation<-factor(df$participation,labels=paste("f.Par",sep="-",levels(df$participation)))
df$foreign<-factor(df$foreign,labels=paste("f.For",sep="-",levels(df$foreign)))
summary(df)
# Target participation - Factor

# Global association entre participation i la resta  de factors

# Global association entre participation i la resta  de numèriques
oneway.test(df$income~df$participation)  # H0: mean income f.Par-Yes = mean income f.Par-NO pvalue=P(H0)= 2 e-7 << 0.05 -> H0 poc creïble -> H0 Rebutja - Income i Participation estan associades

res.cat<-catdes(df,1)
res.cat$quanti.var  # Global association target is factor and explanatory variables numeric
res.cat$quanti
res.cat$test.chi2
res.cat$category

res.con<-condes(df,2) # Target income 
res.con$quanti
res.con$quali
res.con$category

```

Un altre joc de dades

```{r}
library(car)
df<-Prestige
df$census<-NULL
names(df)
res.con<-condes(df,4)  # Target numeric prestige
res.con$quanti
res.con$quali
res.con$category

catdes(df[!is.na(df$type),],5)  # Type target factor
```

