---
title: "Example: Clustering"
author: "L?dia Montero"
date: "2 de abril de 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(FactoMineR)
temperature <- read.table("http://factominer.free.fr/book/temperature.csv",
header=TRUE,sep=";",dec=".",row.names=1)
res.pca <- PCA(temperature[1:23,],scale.unit=TRUE,ncp=2,quanti.sup=13:16,quali.sup=17)
mean(res.pca$eig[,1])  # Kaiser valor propi > 1
sum(res.pca$eig[,1])

summary(res.pca)
res.pca
res.hcpc <- HCPC(res.pca,nb.clust = 4)
names(res.hcpc)

names(res.hcpc$data.clust)
table(res.hcpc$data.clust[,"clust"])

#Description of clusters
res.hcpc$desc.var  # Target clust - catdes()
res.hcpc$desc.var$test.chi2
res.hcpc$desc.var$quanti.var
res.hcpc$desc.var$category
res.hcpc$desc.var$quanti

# Components
res.hcpc$desc.axe
#Paragons and Specic Individuals
res.hcpc$desc.ind

res.hcpc$call$t$within  # TTS = WithSS + BetwSS   1 clust - TTS=WithSS   2clust TTS=5.05+6.75   3 Clusters TTS= 2.72 + (6.75+2.32)     23 Clust TTS = BetwSS

100*(res.hcpc$call$t$within[1]-res.hcpc$call$t$within)/(res.hcpc$call$t$within[1])

res.hcpc$call$t$inert.gain

# kmeans

kc<-kmeans(dist(res.pca$ind$coord[,1:2]),centers=4)
kc
kc$cluster
kc$withinss
kc$tot.withinss
kc$betweenss
kc$totss
100*kc$betweenss/kc$totss

table(kc$cluster,res.hcpc$data.clust$clust)
```
